version: '3.8'

services:
  fake-news-detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fake_news_app_prod
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - LOG_LEVEL=INFO
      - MODEL_NAME=roberta-base
      - WORKERS=4
    volumes:
      - model_cache:/app/.cache/transformers
      - huggingface_cache:/app/.cache/huggingface
      - ./logs:/app/logs
      - ./data:/app/data:ro
    networks:
      - fake-news-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    command: gunicorn --workers 4 --bind 0.0.0.0:8000 --timeout 60 app:app

  redis:
    image: redis:7-alpine
    container_name: fake_news_redis_prod
    volumes:
      - redis_data_prod:/data
    networks:
      - fake-news-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    command: redis-server --appendonly yes --maxmemory 256mb

  nginx:
    image: nginx:alpine
    container_name: fake_news_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - fake-news-detector
    networks:
      - fake-news-network
    restart: always

volumes:
  model_cache:
    driver: local
  huggingface_cache:
    driver: local
  redis_data_prod:
    driver: local

networks:
  fake-news-network:
    driver: bridge
